### PR TITLE
The Web Optimization Project has optimized your repository!

### PR DESCRIPTION
**Pull request by devedse**
# Web Optimization Project (Beta)

The [Web Optimization Project](https://www.github.com/devedse/weboptimizationproject) is a project that will automatically optimizes files in git repositories by compressing them losslessly. This project was created by [Devedse](https://github.com/devedse) in an effort to save the world! :smirk:

If you have any questions, feel free to create an issue or join the gitter chat:
[Join the chat at https://gitter.im/WebOptimizationProject/Lobby](https://gitter.im/WebOptimizationProject/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

## Optimization

The Web Optimization Project optimized this repository. All optimizations (compressions) are done losslessly and no quality / data is lost. This is also verified afterwards by the Wop so you can be sure that your images are exactly the same.

### Commit 1

Information | Value
-- | --
Version | 1.0.0
Support file extension | .PNG .JPG .JPEG .GIF .BMP

#### Statistics

Stats | Value
-- | --
Total optimizable files | 32
Files optimized successfully (size reduced) | 32
Files already fully optimized | 0
Files that failed to be optimized | 0
Total size before optimization | 1.3MB
Total size after optimization | 699.1KB
Optimized size compared to old | 53.36%
Total bytes saved | 611.1KB
Time taken for optimization | 1.1 Hours

#### Files optimized in this repository

FileName | Original Size | Optimized Size | Bytes Saved | Duration | Successful
-- | -- | -- | -- | -- | --
[vue-component-with-p...png](../blob/gh-pages/images/vue-component-with-preprocessors.png) | 206.3KB | 106.3KB | 100KB | 9.9 Minutes | True
[lifecycle.png](../blob/gh-pages/images/lifecycle.png) | 130.8KB | 49.2KB | 81.6KB | 5.3 Minutes | True
[vue-component.png](../blob/gh-pages/images/vue-component.png) | 162.6KB | 84.3KB | 78.3KB | 8.5 Minutes | True
[hn.png](../blob/gh-pages/images/hn.png) | 163.5KB | 92.2KB | 71.2KB | 6.2 Minutes | True
[hn-architecture.png](../blob/gh-pages/images/hn-architecture.png) | 139.5KB | 72.7KB | 66.8KB | 5.3 Minutes | True
[vue-component-with-p...png](../blob/gh-pages/images/vue-component-with-pre-processors.png) | 118.9KB | 66.2KB | 52.7KB | 4.5 Minutes | True
[state.png](../blob/gh-pages/images/state.png) | 34.8KB | 12.6KB | 22.2KB | 2.5 Minutes | True
[data.png](../blob/gh-pages/images/data.png) | 59.2KB | 40.5KB | 18.7KB | 3.3 Minutes | True
[trisoft.png](../blob/gh-pages/images/trisoft.png) | 34.6KB | 18.4KB | 16.2KB | 1.4 Minutes | True
[mvvm.png](../blob/gh-pages/images/mvvm.png) | 42.7KB | 32.2KB | 10.4KB | 3.8 Minutes | True
[components.png](../blob/gh-pages/images/components.png) | 15.9KB | 6.2KB | 9.6KB | 1.6 Minutes | True
[props-events.png](../blob/gh-pages/images/props-events.png) | 25.9KB | 16.9KB | 9KB | 2.2 Minutes | True
[juejin.png](../blob/gh-pages/images/juejin.png) | 14.5KB | 5.6KB | 8.8KB | 38 Seconds | True
[monterail.png](../blob/gh-pages/images/monterail.png) | 14KB | 5.6KB | 8.4KB | 1.2 Minutes | True
[htmlburger.png](../blob/gh-pages/images/htmlburger.png) | 28.2KB | 20.9KB | 7.3KB | 54 Seconds | True
[laravel.png](../blob/gh-pages/images/laravel.png) | 14.8KB | 7.6KB | 7.3KB | 45 Seconds | True
[transition.png](../blob/gh-pages/images/transition.png) | 21.1KB | 14.2KB | 6.9KB | 1.6 Minutes | True
[strikingly.png](../blob/gh-pages/images/strikingly.png) | 9.6KB | 4.4KB | 5.2KB | 20 Seconds | True
[someline.png](../blob/gh-pages/images/someline.png) | 10.2KB | 5.8KB | 4.5KB | 31 Seconds | True
[jsfiddle.png](../blob/gh-pages/images/jsfiddle.png) | 7.4KB | 3.7KB | 3.7KB | 15 Seconds | True
[logo.png](../blob/gh-pages/images/logo.png) | 11.2KB | 7.7KB | 3.5KB | 1.2 Minutes | True
[icons.png](../blob/gh-pages/images/icons.png) | 7.6KB | 4.3KB | 3.4KB | 16 Seconds | True
[actualize.png](../blob/gh-pages/images/actualize.png) | 12.5KB | 9.4KB | 3.1KB | 55 Seconds | True
[chaitin.png](../blob/gh-pages/images/chaitin.png) | 6.9KB | 4.2KB | 2.7KB | 17 Seconds | True
[itunescn.png](../blob/gh-pages/images/itunescn.png) | 4.8KB | 2.3KB | 2.5KB | 26 Seconds | True
[patreon.png](../blob/gh-pages/images/patreon.png) | 5.5KB | 3.2KB | 2.3KB | 22 Seconds | True
[search.png](../blob/gh-pages/images/search.png) | 2KB | 609B | 1.4KB | 11 Seconds | True
[down.png](../blob/gh-pages/images/down.png) | 1.5KB | 411B | 1.1KB | 10 Seconds | True
[feed.png](../blob/gh-pages/images/feed.png) | 1.4KB | 378B | 1KB | 10 Seconds | True
[paypal.png](../blob/gh-pages/images/paypal.png) | 1.7KB | 716B | 988B | 10 Seconds | True
[check.png](../blob/gh-pages/images/check.png) | 363B | 203B | 160B | 10 Seconds | True
[menu.png](../blob/gh-pages/images/menu.png) | 193B | 125B | 68B | 10 Seconds | True

### CODE REVIEW

**Comment by yyx990803** [comment]
While I appreciate the optimizations, mass spamming PRs like this is not cool. Please stop doing this.

**Comment by devedse** [comment]
Thanks for your comment, I've stopped running the tool.

Can you please elaborate a bit on why exactly you do like optimizations but are not interested in accepting this pull request with optimizations? (I've created this tool in my spare time with the only goal to save some wasted storage space/network bandwith, even if it's just a few bytes, without having any negative side effects).

**Comment by niutech** [comment]
Exactly. Optimized images mean faster web and less data. @devedse keep up your good work!

**Comment by yyx990803** [comment]
Because I maintain multiple repos so my inbox gets flooded by your automated PRs, with some of them being submitted to repos that have no need to optimization at all. I understand this is a good will project but nobody likes being spammed by bots.

**Pull request closed without merging**
